### ISSUE TITLE
64 positions while compiling ?

### ISSUE THREAD

**Issue by tissatussa** [FireFather/fire-NN#10]
i compiled myself (on Xubuntu 20.04 by 'make profile-build ARCH=...') and it takes a long time .. in the process i see 64 positions being 'examinated'.  What is this?  Is an optimal binary being compiled by testing the eval results of these 64 positions on the concerning hardware?  What if other positions are used? - can the user compile some own binary by using another set of (64) positions?  Then how?

**Comment by FireFather** [comment]
the positions are used for P.G.O. (profile guided optimization)

which is called via the keyword 'profile' in the
 'make profile-build ARCH=' command

see
https://en.wikipedia.org/wiki/Profile-guided_optimization

it's preferable to specify an system architecture for the 'make profile-build ARCH=' command

for example:
make profile-build ARCH= x86-64-avx2

Fire supports 3 architectures:
 @echo "x86-64-popc             > x86 64-bit with popcnt support"
 @echo "x86-64-avx2              > x86 64-bit with avx2 support"
 @echo "x86-64-bmi2             > x86 64-bit with bmi2 support"

popcnt is very very slow...
avx2 and/or bmi2 are the best, both very fast

try compiling with
make profile-build ARCH= x86-64-avx2
or
make profile-build ARCH= x86-64-bmi2

and you'll likely see an enormous speed improvement

**Comment by FireFather** [comment]
What is this? Is an optimal binary being compiled by testing the eval results of these 64 positions on the concerning hardware? 
**yes**

What if other positions are used? - can the user compile some own binary by using another set of (64) positions? Then how?

**yes**, other positions can be used, but this will likely not improve the binary
at this time Fire uses:
the start position, 20 opening positions, 20 middlegame positions, 20 endgame positions, and 3 FRC (Chess 960) start positions	
during profile guided optimization	

these positions are specified in the source code...see /util/bench.h

**Comment by tissatussa** [comment]
thanks for this complete answer !
unfortunately my laptop can not do AVX / BMI ..

**Comment by tissatussa** [comment]
i wonder, does your code specifically run faster "with AVX2" or does any code run faster with it ?
btw. i just happen to get a rather new laptop which can do AVX2 plus BMI2 !
