### ISSUE TITLE
Fire Eval Completely incorrect, random pushing pawns?

### ISSUE THREAD

**Issue by Zovixi** [FireFather/fire-NN#12]
![image](https://user-images.githubusercontent.com/94098735/141243735-cde7d297-4707-4e75-8900-4a7d6fa38345.png)
Eval assumes that a3 a6 will happen, this is on every fire version that i have, in every uci compliant program that i own. Typically, when in an engine match, fire will just crash when it calculates mate, forgot to mention, when it calculates checkmate, it will defend mate perfectly.

**Comment by FireFather** [comment]
That's the evaluation when the neural network evaluation file 'raptor.bin' has not been loaded. (ie no position evaluation whatsoever).  A suitable NNUE file is required for Fire to run properly.
This file is critical to Fire's strength.  When loaded, it's very strong.
https://www.sp-cc.de/

Please download the release archive from here: https://github.com/FireFather/fire/releases/tag/Fire_8.NN.MC.3 and verify that raptor.bin is being loaded.  You can double click on the .exe and look for the following message in the console prompt:

![image](https://user-images.githubusercontent.com/3767526/141249716-cd9ec0e1-6245-436a-b38b-4800df828dea.png)

**Comment by Zovixi** [comment]
Raptor.bin is found when running both bmi2 and avx2. However, when still running in uci compliant programs, the evaluated moves are the exact same
![image](https://user-images.githubusercontent.com/94098735/141302170-355f5971-ce1e-4dff-bd16-2498c9b3ea98.png)

Note: I did allow Fire to use about 100mb of memory vs the like 10 or 5 that the program i showed you earlier allowed, and it seemed to play different moves. Is it possible that it just needed more memory?
Edit: The program still crashes till near the end of the game, making matches impossible to finish, this only happens when Fire is running

**Comment by Zovixi** [comment]
Something on my edit from my previous comment
Whenever Fire calculates mate (from either side) it typically (not all the time) crashes ShredderChess
![image](https://user-images.githubusercontent.com/94098735/141304348-092ca5c5-2de0-4758-85ed-922ba4feb440.png)

**Comment by FireFather** [comment]
Windows is indicating that the Shredder executable crashed...
if you check task manager, I suspect you'll see that Fire is still running.

Fire is running flawlessly in Shredder 12 in Frank's tournament:
https://www.amateurschach.de/fling/fcp-tourney-2022.html
https://www.amateurschach.de/

Might your issue have something to do with syzygy table bases?
Also: perhaps you may need to specify to Shredder the full path of raptor.bin, although it appears from the game you posted above that Fire is moving correctly now.  Did you resolve that issue?

**Comment by FireFather** [comment]
In shredder I guess pb = permanent brain (better known as ponder)...
I suggest you try turning that off.  Ponder 'on' is rarely (if ever) used, especially in tournaments and rating lists
and some engines don't even support it.

**Comment by Zovixi** [comment]
Shredders Permanent Brain did infact hinder fire, i don't know why it would, but thank you so much for the fix.
if you would like, i can send you the results of this tournament which your engine is performing in.
Once again, thanks much for the fix
