### ISSUE TITLE
Hello, can you issue a Chinese chess engine

### ISSUE THREAD

**Issue by shuangqiao999** [FireFather/fire-NN#13]
Many people like Chinese chess (xiangqi) really hope you can release a Chinese chess (xiangqi) engine

**Comment by calcitem** [comment]
The author is not Chinese, why do you ask him to release Xiangqi engine?

**Comment by FireFather** [comment]
Sounds extremely challenging, but a bit more than I'd like to bite off and chew at the moment...
Thanks for the suggestion anyway!

**Comment by shuangqiao999** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
