### ISSUE TITLE
link to NN download is dead

### ISSUE THREAD

**Issue by tissatussa** [FireFather/fire-NN#16]
in your README : https://www.comp.nus.edu.sg/~sergio-v/nnue/ ?

**Comment by FireFather** [comment]
ok, thx
that link is to The National University of Singapore...
they must have changed or removed  Sergio's home page

In any case, there is a copy of Raptor.bin in the Release download
https://github.com/FireFather/fire-NN/releases/tag/Fire_8.NN.MC.3
