### ISSUE TITLE
Makefile error

### ISSUE THREAD

**Issue by MichaelB7** [FireFather/fire-NN#3]
Norman, on my Msys2 installation

I had to undo this change in randome.cpp, line 23, commit 270bf177b6b2d, the line bolded is what I had to use

// calculate a uniform distribution between 1 and num_moves + 1
	**std::uniform_real_distribution<> distribution (1, num_moves + 1);**
	//const std::uniform_real_distribution<> distribution (1, static_cast<double>(num_moves) + static_cast<double>(1));

I also picked up over 1% in NPS by adding this line 74 in the Makefile:
	**CXXFLAGS += -flto -mavx2**

**Comment by FireFather** [comment]
thanks much for this Mike... 
I should have tested that change more thoroughly... 
as you prob well know, what compiles fine in Visual Studio may not do well elsewhere 

I'll fix the source code as soon as i can.. 

my best regards, 
Norm 




From: "Michael Byrne" ***@***.***> 
To: "FireFather/fire" ***@***.***> 
Cc: "Subscribed" ***@***.***> 
Sent: Friday, April 30, 2021 10:45:25 PM 
Subject: [FireFather/fire] Makefile error (#3) 





Norman, on my Msys2 installation, I had to add the line bolded in the Makefile line 74 

ifeq ($(COMP),mingw) 
comp=mingw 
LDFLAGS += -lgcov 

and undo this change in randome.cpp, line 23, commit [ https://github.com/FireFather/fire/commit/270bf177b6b2db855e2b4a77820a483542b5bc2c | 270bf17 ] , the line bolded is what I had to use 

// calculate a uniform distribution between 1 and num_moves + 1 
std::uniform_real_distribution<> distribution (1, num_moves + 1); 
//const std::uniform_real_distribution<> distribution (1, static_cast(num_moves) + static_cast(1));
