### ISSUE TITLE
multiPV

### ISSUE THREAD

**Issue by ghost** [FireFather/fire-NN#4]
I downloaded the latest version of fire to use as an analysis.
I am under linux.

when i select 3 lines in multiPV, i have only 1 line displayed.
![Capture d’écran du 2021-06-02 11-29-35](https://user-images.githubusercontent.com/77933011/120457334-a6730a80-c396-11eb-8781-3ca074bf639d.png)

**Comment by FireFather** [comment]
Thanks for pointing this out.  Completely missed in my testing (I never use multipv).
I've fixed it by defining uci_multipv as an inline variable.
see uci.h

I'll be uploading new binaries later today.

**Comment by ghost** [comment]
thank you,
![kisspng-smiley-thumb-signal-emoticon-clip-art-smily-5b4984d8c3ca23 307600191531544792802(1)](https://user-images.githubusercontent.com/77933011/120492321-42fad400-c3ba-11eb-9c89-4d2e198f8299.png)
