### ISSUE TITLE
Ponder is broken on certain situations

### ISSUE THREAD

**Issue by CMCanavessi** [FireFather/fire-NN#6]
I've noticed that sometimes Fire sends "bestmove" while pondering before it is its turn to move. For example:

Start of the game, Fire vs. X
Fire thinks and plays a move, starts pondering on opponent's move
While opponent is thinking, Fire is done and plays a new move (should keep thinking AT LEAST until the opponent moves, and then move instantly).
The opponent finishes thinking, plays a move, and even if it was the move that Fire guessed, Fire has to start thinking again (no ponderhit).

I've attached a log from BanksiaGUI that shows this behaviour in the 1st move of the game.

[Fire.txt](https://github.com/FireFather/fire/files/6911747/Fire.txt)

**Comment by FireFather** [comment]
Hi Carlos-

I think I know exactly where and why...
I'll take a look and try to fix

Thanks for the bug report!

**Comment by FireFather** [comment]
HI Carlos,
I've made a couple changes in Fire_8.NN.MC.2 concerning ponder.
Please give this a try to see if it resolves the issue.

**Comment by CMCanavessi** [comment]
Norman, the ponder issue is not fixed. Latest 8.NN.MC.2 is behaving the same way. 
The TB loading issue seems ok so far from what I've tried.

**Comment by CMCanavessi** [comment]
Fire 8.NN.MC.2 > bestmove f7f5 ponder b1c3
Fire 8.NN.MC.2 < position fen rnknrbbq/pppppppp/8/8/8/8/PPPPPPPP/RNKNRBBQ w EAea - 0 1 moves f2f4 f7f5 b1c3
Fire 8.NN.MC.2 < go ponder wtime 1743253 btime 1693412 winc 5000 binc 5000
Minic 3.09 < position fen rnknrbbq/pppppppp/8/8/8/8/PPPPPPPP/RNKNRBBQ w EAea - 0 1 moves f2f4 f7f5
Minic 3.09 < go wtime 1743253 btime 1693412 winc 5000 binc 5000
.
.
.
Fire 8.NN.MC.2 > bestmove g7g6 ponder e2e4

**Comment by FireFather** [comment]
Thanks

apparently, when using Arena, this behavior doesn't disturb the game ...
2021-08-03 23:19:26.559<--1:bestmove b1c3 ponder d7d6
2021-08-03 23:19:26.559*1*Bestmove was from pondersearch, ignoring
Arena simply ignores the bestmove statement

I'll investigate futher
http://wbec-ridderkerk.nl/html/UCIProtocol.html

to see what I can do

**Comment by CMCanavessi** [comment]
Yes, but even if it GUIs ignore it, it shouldn't be sent. Engine should search while pondering non-stop.

**Comment by FireFather** [comment]
I understand what you're saying

Here's the UCI spec:	
* ponder
		start searching in pondering mode.
		Do not exit the search in ponder mode, even if it's mate!
		This means that the last move sent in in the position string is the ponder move.
		The engine can do what it wants to do, but after a "ponderhit" command
		it should execute the suggested move to ponder on. This means that the ponder move sent by
		the GUI can be interpreted as a recommendation about which move to ponder. However, if the
		engine decides to ponder on a different move, it should not display any mainlines as they are
		likely to be misinterpreted by the GUI because the GUI expects the engine to ponder
	        on the suggested move.
* ponderhit
	the user has played the expected move. This will be sent if the engine was told to ponder on the same move
	the user has played. The engine should continue searching but switch from pondering to normal search.

**Comment by FireFather** [comment]
I will consider waiting for a 'stop' when pondering for a possible future release...but since the current implementation does no harm, I won't consider it as an urgent issue.

Thanks for your help!
