### ISSUE TITLE
Self play training

### ISSUE THREAD

**Issue by 3dmatch** [FireFather/fire-NN#8]
Hello. 
fire is one of the best chess engines. But I have found that fire 8 classic has a realistic positional evaluation
Than nnue engine. I think the reason is
Fire use sf and cfish nets. My individual idea is that  if fire use a self play training net it would be one of the best and even the best cpu engine for human training. 

Homayoun

**Comment by FireFather** [comment]
Hi Homayoun,

Thanks for your comments
Please feel free to create and train a self-play net for Fire.
I'd be happy to include it for download from this repository.

Best regards,
Norm
