### ISSUE TITLE
Chess 960 castling syntax

### ISSUE THREAD

**Issue by CMCanavessi** [FireFather/fire-NN#9]
Hey Norman, I've found another issue. Castling is broken (for most GUIs, except maybe Arena) in newer Fire versions.

Try this FEN: r1b3kr/ppp4p/3p1bpB/4n3/8/3P4/PPP1N1PP/R2BK2R w KQ - 2 12

You will see that Fire wants to play "e1g1". This is wrong and produces an "Illegal move" in most chess 960 compiant GUIs, king-side castling in this position should be e1h1 ("king takes rook").
I  have tried several versions and found that Fire 8 is ok, Fire 8.1 is broken, 8.11 is broken, 8.NN.1 is broken, etc...
So it must be some change between Fire 8 and Fire 8.11 that broke compatibility with FRC.

**Comment by FireFather** [comment]
thanks for letting me know and spending time tracking it down, 
I'll address this as soon as I have time

**Comment by CMCanavessi** [comment]
I think the problem is here: 

```
	if (castling_possible(white_short))
		ss << (chess960_ ? static_cast<char>('A' + file_of(castle_rook_square(g1))) : 'K');

	if (castling_possible(white_long))
		ss << (chess960_ ? static_cast<char>('A' + file_of(castle_rook_square(c1))) : 'Q');

	if (castling_possible(black_short))
		ss << (chess960_ ? static_cast<char>('a' + file_of(castle_rook_square(g8))) : 'k');

	if (castling_possible(black_long))
		ss << (chess960_ ? static_cast<char>('a' + file_of(castle_rook_square(c8))) : 'q');
		
```
g1, g8, c1 and c8 are hardcoded for chess 960. They shouldn't be.

**Comment by FireFather** [comment]
I've just released Fire_8.NN.MC.3.x64 which should fix this...
Thanks again Carlos
